##################################################
# Ansible initialisation script
##################################################
---
- hosts: all
  collections:
    - community.mysql
    - community.docker
    - community.general
  become: true
  vars_files:
    - vars/default.yml

# Check server status - must be answer
  tasks:
    - action: ping

    - name: Install start packages
      apt: 
        name={{ item }} 
        update_cache=yes 
        state=latest
      loop: 
        - python3-pymysql
        - mc
        - snapd
        - net-tools
        - make
        - git
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - python3-pip
        - virtualenv
        - python3-setuptools
 

# Nginx Configuration
    - name: Install Nginx
      when: "'web' in group_names"
      apt: 
        name=nginx 
        update_cache=yes 
        state=latest

#Docker install block
    - name: Add Docker GPG apt Key
      when: "'docker' in group_names"
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      when: "'docker' in group_names"
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      when: "'docker' in group_names"
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Update apt and install docker-ce
      when: "'docker' in group_names"
      apt:
        name: docker-compose-plugin
        state: latest
        update_cache: true

    - name: Install Docker Module for Python
      when: "'docker' in group_names"
      pip:
        name: docker

#MySQL block
    - name: Add Docker GPG apt Key
      when: "'mysql' in group_names"
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      when: "'mysql' in group_names"
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      when: "'mysql' in group_names"
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Update apt and install docker-ce
      when: "'mysql' in group_names"
      apt:
        name: docker-compose-plugin
        state: latest
        update_cache: true

    - name: Install Docker Module for Python
      when: "'mysql' in group_names"
      pip:
        name: docker

    - name: Install Docker compose module
      when: "'docker' in group_names"
      pip:
        name: docker-compose    

    - name: copy docker-compose
      when: "'mysql' in group_names"
      copy:
        src: ./files/docker-compose.yml
        dest: $HOME/docker-compose.yml

    - name: run docker-compose
      when: "'mysql' in group_names"
      docker_compose:
        project_src: $HOME
        build: yes
      register: output