---
##################################################
# Server initialisation script
##################################################
- name: Server initialization
  hosts: all
  collections:
    - community.mysql
    - community.docker
    - community.general
  become: true
  roles:
    - role: initial_soft 

    - role: install_docker  
      tags: docker

    - role: deploy_mysql
      tags: mysql


  tasks:
  - name: Install Nginx
    tags: web
    ansible.builtin.apt:
      name: nginx
      update_cache: yes
      state: latest

