---
##################################################
# Server initialisation script
##################################################
- name: Server initialization
  hosts: all
  collections:
    - community.mysql
    - community.docker
    - community.general
  become: true
  vars_files:
    - inventory/group_vars/all/default.yml
  roles:
    - initial_soft 
    
# Docker install block
- hosts: docker
  collections:
    - community.mysql
    - community.docker
    - community.general
  become: true
  vars_files:
    - inventory/group_vars/all/default.yml
  roles:
    - install_docker

# MySQL block
- hosts: mysql
  collections:
    - community.mysql
    - community.docker
    - community.general
  become: true
  vars_files:
    - inventory/group_vars/all/default.yml
  roles:
    - install_docker
    - deploy_mysql
  
# Web server blocks
- hosts: web
  collections:
    - community.mysql
    - community.docker
    - community.general
  become: true
  tasks:
  - name: Install Nginx
    ansible.builtin.apt:
      name: nginx
      update_cache: yes
      state: latest

