---
# tasks file for deploy_mysql
- name: main | Creates directory
  file:
    path: "{{ MYSQL_PATH }}"
    state: directory

- name: main | Copy docker-compose
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: "{{ MYSQL_PATH }}/docker-compose.yml"

- name: main | Copy env-file as template
  ansible.builtin.template:
    src: m8.j2
    dest: "{{ MYSQL_PATH }}/m8.env"



- name: main | Run docker-compose
  community.docker.docker_compose:
    project_src: "{{ MYSQL_PATH }}"
    build: yes
  register: output
